name: 'Pen Design Review'
description: 'Automatically preview .pen design files in pull requests'
author: 'RemoteState'

branding:
  icon: 'book-open'
  color: 'blue'

inputs:
  github-token:
    description: 'GitHub token for API access (usually secrets.GITHUB_TOKEN)'
    required: true

  review-mode:
    description: 'Review mode: "full" (render all frames) or "diff" (show only changes with before/after comparison)'
    required: false
    default: 'diff'

  service-url:
    description: 'Screenshot rendering API URL'
    required: false
    default: 'https://pencil.remotestate.com'

  service-api-key:
    description: 'API key for higher limits (5,000/month). Without a key, free tier gives 1,000/month via GitHub OIDC (requires "permissions: id-token: write"). Contact us for 10,000/month.'
    required: false

  comment-mode:
    description: 'How to post comments: "create" (always new), "update" (update existing), "none" (skip commenting)'
    required: false
    default: 'update'

  comment-id:
    description: 'Unique identifier to namespace PR comments. Allows multiple workflows to post separate comments on the same PR without overwriting each other.'
    required: false
    default: ''

  upload-artifacts:
    description: 'Whether to upload screenshots as workflow artifacts'
    required: false
    default: 'true'

  include-deleted:
    description: 'Whether to show deleted files in the comment'
    required: false
    default: 'true'

  max-frames-per-file:
    description: 'Maximum number of frames to render per .pen file (0 for unlimited)'
    required: false
    default: '20'

  image-format:
    description: 'Output image format: "webp" (smallest), "png", or "jpeg"'
    required: false
    default: 'webp'

  image-scale:
    description: 'Export scale: 1, 2, or 3'
    required: false
    default: '2'

  image-quality:
    description: 'Image quality for webp/jpeg (1-100)'
    required: false
    default: '90'

outputs:
  screenshots-path:
    description: 'Path to the directory containing generated screenshots'

  changed-files:
    description: 'JSON array of changed .pen files'

  frames-rendered:
    description: 'Total number of frames rendered'

  comment-id:
    description: 'ID of the created/updated PR comment'

runs:
  using: 'node20'
  main: 'dist/index.js'
