/**
 * PR Comment Builder
 *
 * Generates markdown for PR comments with design review information
 */

import {
  CommentData,
  PenFileCommentData,
  FrameCommentData,
  CommentSummary,
  FileStatus,
} from './types';

// Unique identifier for our comments (for upsert logic)
export const COMMENT_MARKER = '<!-- pencil-design-review -->';

/**
 * Escape markdown special characters in user-controlled strings
 */
function escapeMarkdown(text: string): string {
  return text.replace(/[[\]()|\\_*`~#>!]/g, '\\$&');
}

/**
 * Build the full PR comment markdown
 */
export function buildComment(data: CommentData): string {
  const lines: string[] = [
    COMMENT_MARKER,
    '',
    '## 🎨 Design Review',
    '',
    buildSummarySection(data.summary),
    '',
  ];

  // Add each file section
  for (const file of data.files) {
    lines.push(buildFileSection(file));
    lines.push('');
  }

  // Add footer
  lines.push('---');
  lines.push(buildFooter(data.commitSha));

  return lines.join('\n');
}

/**
 * Build the summary section
 */
function buildSummarySection(summary: CommentSummary): string {
  const parts: string[] = [];

  if (summary.addedFiles > 0) {
    parts.push(`**${summary.addedFiles}** added`);
  }
  if (summary.modifiedFiles > 0) {
    parts.push(`**${summary.modifiedFiles}** modified`);
  }
  if (summary.deletedFiles > 0) {
    parts.push(`**${summary.deletedFiles}** deleted`);
  }

  const filesSummary = parts.length > 0 ? parts.join(', ') : 'No changes';

  const lines = [
    `📁 **${summary.totalFiles}** design file${summary.totalFiles !== 1 ? 's' : ''} (${filesSummary})`,
    `🖼️ **${summary.totalFrames}** frame${summary.totalFrames !== 1 ? 's' : ''} detected`,
  ];

  if (summary.successfulRenders > 0) {
    lines.push(`✅ **${summary.successfulRenders}** rendered successfully`);
  }

  if (summary.failedRenders > 0) {
    lines.push(`❌ **${summary.failedRenders}** failed to render`);
  }

  return lines.join('\n');
}

/**
 * Build section for a single file
 */
function buildFileSection(file: PenFileCommentData): string {
  const statusIcon = getStatusIcon(file.status);
  const statusLabel = getStatusLabel(file.status);

  const lines: string[] = [
    `### ${statusIcon} \`${file.path}\` (${statusLabel})`,
    '',
  ];

  if (file.frames.length === 0) {
    lines.push('_No frames found in this file_');
    return lines.join('\n');
  }

  // Check if we have any screenshots (visual mode)
  const hasScreenshots = file.frames.some(f => f.screenshotUrl || f.screenshotPath);

  if (hasScreenshots) {
    // Visual mode: show screenshots
    for (const frame of file.frames) {
      lines.push(buildFrameWithScreenshot(frame));
      lines.push('');
    }
  } else {
    // Metadata mode: show table
    lines.push(buildFrameTable(file.frames));
  }

  return lines.join('\n');
}

/**
 * Build a frame section with screenshot (visual mode)
 */
function buildFrameWithScreenshot(frame: FrameCommentData): string {
  const lines: string[] = [];

  lines.push(`#### ${escapeMarkdown(frame.name)}`);

  if (frame.error) {
    lines.push(`> ⚠️ Failed to render: ${escapeMarkdown(frame.error)}`);
  } else if (frame.screenshotUrl) {
    lines.push(`![${escapeMarkdown(frame.name)}](${frame.screenshotUrl})`);
  } else if (frame.screenshotPath) {
    // If we have a path but no URL, show the path as reference
    lines.push(`> Screenshot saved to: \`${frame.screenshotPath}\``);
  }

  return lines.join('\n');
}

/**
 * Build a table of frames (metadata mode)
 */
function buildFrameTable(frames: FrameCommentData[]): string {
  const lines: string[] = [
    '| Frame | ID | Status |',
    '|-------|-----|--------|',
  ];

  for (const frame of frames) {
    const status = frame.error ? `❌ ${escapeMarkdown(frame.error)}` : '✅ OK';
    lines.push(`| ${escapeMarkdown(frame.name)} | \`${frame.id}\` | ${status} |`);
  }

  return lines.join('\n');
}

/**
 * Build the footer
 */
function buildFooter(commitSha: string): string {
  const shortSha = commitSha.substring(0, 7);
  return `_Generated by [Pencil Design Review](https://github.com/remotestate/pencil-actions) for commit ${shortSha}_`;
}

/**
 * Get icon for file status
 */
function getStatusIcon(status: FileStatus): string {
  switch (status) {
    case 'added':
      return '🆕';
    case 'modified':
      return '📝';
    case 'deleted':
      return '🗑️';
    case 'renamed':
      return '📋';
    default:
      return '📄';
  }
}

/**
 * Get label for file status
 */
function getStatusLabel(status: FileStatus): string {
  switch (status) {
    case 'added':
      return 'added';
    case 'modified':
      return 'modified';
    case 'deleted':
      return 'deleted';
    case 'renamed':
      return 'renamed';
    default:
      return 'changed';
  }
}

/**
 * Calculate summary statistics from file data
 */
export function calculateSummary(files: PenFileCommentData[]): CommentSummary {
  let totalFrames = 0;
  let successfulRenders = 0;
  let failedRenders = 0;
  let addedFiles = 0;
  let modifiedFiles = 0;
  let deletedFiles = 0;

  for (const file of files) {
    totalFrames += file.frames.length;

    for (const frame of file.frames) {
      if (frame.error) {
        failedRenders++;
      } else {
        successfulRenders++;
      }
    }

    switch (file.status) {
      case 'added':
        addedFiles++;
        break;
      case 'modified':
        modifiedFiles++;
        break;
      case 'deleted':
        deletedFiles++;
        break;
    }
  }

  return {
    totalFiles: files.length,
    totalFrames,
    successfulRenders,
    failedRenders,
    addedFiles,
    modifiedFiles,
    deletedFiles,
  };
}

/**
 * Build a minimal comment for when there are no design changes
 */
export function buildNoChangesComment(): string {
  return [
    COMMENT_MARKER,
    '',
    '## 🎨 Design Review',
    '',
    '_No `.pen` design files were changed in this PR._',
    '',
  ].join('\n');
}
